<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MIIPL_ON_Rajendra_Mane" failures="1" tests="5" name="SOR_testcases.SOR_LoginTestCase" time="40.443" errors="0" timestamp="2024-10-11T12:51:38 IST" skipped="0">
  <testcase classname="SOR_testcases.SOR_LoginTestCase" name="Check_Valid_Credentials" time="8.113"/>
  <system-out/>
  <testcase classname="SOR_testcases.SOR_LoginTestCase" name="check_Blank_Username" time="4.877">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at SOR_Pages.SOR_Login_Page.Balnk_UserName(SOR_Login_Page.java:76)
at SOR_testcases.SOR_LoginTestCase.check_Blank_Username(SOR_LoginTestCase.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- check_Blank_Username -->
  <system-out/>
  <testcase classname="SOR_testcases.SOR_LoginTestCase" name="check_Blank_Password" time="5.077"/>
  <system-out/>
  <testcase classname="SOR_testcases.SOR_LoginTestCase" name="check_InValid_Password" time="15.742"/>
  <system-out/>
  <testcase classname="SOR_testcases.SOR_LoginTestCase" name="check_InValid_User_Name" time="6.634"/>
  <system-out/>
</testsuite> <!-- SOR_testcases.SOR_LoginTestCase -->
